#!/bin/bash
set -e

component=../node_modules/component/bin/component
browserify=../node_modules/browserify/bin/cmd.js

# install components
component install
mkdir -p tmp

# build local version of tape
browserify ./node_modules/tape/index.js --standalone tape --outfile tmp/tape.js

# build component version of abstract test suite
cd test/abstract-leveldown
component build --no-require --out ../../tmp --name abstract-test-suite
cd ../..
